### ISSUE TITLE
Alpha bug & feature checklist

### ISSUE THREAD

**Issue by Friendly0Fire** [Friendly0Fire/GW2Radial#151]
# Bugs

* [x] Fix `ScanCode` ordering, especially for modifiers: should be Ctrl, Alt, Shift
* [x] Hide/gray out `noHoldOption_` when `clickSelectOption_` is on and vice-versa
* [x] Fix PNG transparency compatibility
* [x] Ensure delayed input is cleared when switching characters/maps
* [x] Move delayed input circle/progress bar to somewhere on the bottom bar rather than on the mouse
* [x] Fallback to shaders zip if shaders cannot be found in Debug mode
* [x] Need some kind of tab scroll for the menu when lots of tabs (wheels) are loaded
* [x] Check Skimmer code against EotN and Elon Riverlands, add option to turn off

# Features

* [x] Restructure each wheel to have "conditions" for when to enable/disable the wheel, allowing multiple wheels to use the same activating keybinds under different circumstances
  * [x] In/out of combat
  * [x] Professions
  * [x] Map type/id
* [x] Parallel to the point above, refine keybind conflicts detection to take conditions into account
* [x] Optionally make the center region of the wheel cancel a queued mount command instead of its normal behavior
